#!/bin/sh
set -e

echo "Step 1/2: Setting up a python virtualenv"
virtualenv .
. ./bin/activate


echo "Step 2/2: Installing python packages"

python setup.py install
pip install pep8
pip install coverage

deactivate
