#!/bin/sh
set -e
GIT_ROOT=$(git rev-parse --show-toplevel)


if [ ! "${CI}" = "true" ] # Skip when running Travis
then
  [ -n "${VIRTUAL_ENV}" ] || source "${GIT_ROOT}"/bin/activate
fi

cd "${GIT_ROOT}"
pep8 --exclude=tests *.py "${GIT_ROOT}"/cnxeasybake/
pep8 --max-line-length=1000 "${GIT_ROOT}"/cnxeasybake/tests

coverage run --source=cnxeasybake setup.py test

# Note: deactivate is not necessary because the virtualenv is deactivated at the end of the script
