#!/bin/sh
set -e

if [ ! "${CI}" == "true" ] # Skip when running Travis
then
  . ./bin/activate
fi

pep8 --exclude=tests *.py cnxeasybake/
pep8 --max-line-length=1000 cnxeasybake/tests

coverage run --source=cnxeasybake setup.py test

if [ ! "${CI}" == "true" ] # Skip when running Travis
then
  deactivate
fi
